/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/indexDecorate/modelList/Carousel.vue')['default']
    Carousel1: typeof import('./src/components/indexDecorate/modelList/Carousel1.vue')['default']
    Carousel2: typeof import('./src/components/indexDecorate/modelList/Carousel2.vue')['default']
    CateNav: typeof import('./src/components/nav/CateNav.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FirstPageAdvert: typeof import('./src/components/indexDecorate/modelList/FirstPageAdvert.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    ForYour: typeof import('./src/components/indexDecorate/modelList/ForYour.vue')['default']
    GoodsAndType: typeof import('./src/components/indexDecorate/modelList/GoodsAndType.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    MixBrand: typeof import('./src/components/indexDecorate/modelList/mixs/MixBrand.vue')['default']
    MixGoods: typeof import('./src/components/indexDecorate/modelList/mixs/MixGoods.vue')['default']
    MixModel: typeof import('./src/components/indexDecorate/modelList/MixModel.vue')['default']
    ModelForm: typeof import('./src/components/indexDecorate/ModelForm.vue')['default']
    ModelFormItem: typeof import('./src/components/indexDecorate/ModelFormItem.vue')['default']
    NewGoodsSort: typeof import('./src/components/indexDecorate/modelList/NewGoodsSort.vue')['default']
    NotEnough: typeof import('./src/components/indexDecorate/modelList/NotEnough.vue')['default']
    OneRowThreeColumns: typeof import('./src/components/indexDecorate/modelList/OneRowThreeColumns.vue')['default']
    OnlyGoodsModel: typeof import('./src/components/indexDecorate/modelList/OnlyGoodsModel.vue')['default']
    Recommend: typeof import('./src/components/indexDecorate/modelList/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Seckill: typeof import('./src/components/indexDecorate/modelList/Seckill.vue')['default']
    Verify: typeof import('./src/components/verify/index.vue')['default']
  }
}
